const grid = [
  [
    { current: 0, actual: 7, moddable: true },
    { current: 2, actual: 2, moddable: false },
    { current: 0, actual: 8, moddable: true },
    { current: 0, actual: 5, moddable: true },
    { current: 4, actual: 4, moddable: false },
    { current: 6, actual: 6, moddable: false },
    { current: 0, actual: 3, moddable: true },
    { current: 0, actual: 9, moddable: true },
    { current: 0, actual: 1, moddable: true },
  ],
  [
    { current: 0, actual: 6, moddable: true },
    { current: 0, actual: 1, moddable: true },
    { current: 0, actual: 4, moddable: true },
    { current: 0, actual: 3, moddable: true },
    { current: 8, actual: 8, moddable: false },
    { current: 0, actual: 9, moddable: true },
    { current: 2, actual: 2, moddable: false },
    { current: 0, actual: 5, moddable: true },
    { current: 0, actual: 7, moddable: true },
  ],
  [
    { current: 5, actual: 5, moddable: false },
    { current: 0, actual: 9, moddable: true },
    { current: 0, actual: 3, moddable: true },
    { current: 0, actual: 2, moddable: true },
    { current: 0, actual: 7, moddable: true },
    { current: 1, actual: 1, moddable: false },
    { current: 8, actual: 8, moddable: false },
    { current: 4, actual: 4, moddable: false },
    { current: 6, actual: 6, moddable: false },
  ],
  [
    { current: 8, actual: 8, moddable: false },
    { current: 7, actual: 7, moddable: false },
    { current: 9, actual: 9, moddable: false },
    { current: 1, actual: 1, moddable: false },
    { current: 0, actual: 3, moddable: true },
    { current: 0, actual: 4, moddable: true },
    { current: 0, actual: 6, moddable: true },
    { current: 0, actual: 2, moddable: true },
    { current: 5, actual: 5, moddable: false },
  ],
  [
    { current: 2, actual: 2, moddable: false },
    { current: 3, actual: 3, moddable: false },
    { current: 6, actual: 6, moddable: false },
    { current: 0, actual: 7, moddable: true },
    { current: 9, actual: 9, moddable: false },
    { current: 5, actual: 5, moddable: false },
    { current: 0, actual: 4, moddable: true },
    { current: 1, actual: 1, moddable: false },
    { current: 0, actual: 8, moddable: true },
  ],
  [
    { current: 1, actual: 1, moddable: false },
    { current: 0, actual: 4, moddable: true },
    { current: 5, actual: 5, moddable: false },
    { current: 8, actual: 8, moddable: false },
    { current: 0, actual: 6, moddable: true },
    { current: 0, actual: 2, moddable: true },
    { current: 0, actual: 9, moddable: true },
    { current: 0, actual: 7, moddable: true },
    { current: 3, actual: 3, moddable: false },
  ],
  [
    { current: 4, actual: 4, moddable: false },
    { current: 0, actual: 8, moddable: true },
    { current: 0, actual: 1, moddable: true },
    { current: 9, actual: 9, moddable: false },
    { current: 0, actual: 5, moddable: true },
    { current: 0, actual: 3, moddable: true },
    { current: 7, actual: 7, moddable: false },
    { current: 0, actual: 6, moddable: true },
    { current: 0, actual: 2, moddable: true },
  ],
  [
    { current: 3, actual: 3, moddable: false },
    { current: 6, actual: 6, moddable: false },
    { current: 2, actual: 2, moddable: false },
    { current: 4, actual: 4, moddable: false },
    { current: 1, actual: 1, moddable: false },
    { current: 0, actual: 7, moddable: true },
    { current: 5, actual: 5, moddable: false },
    { current: 0, actual: 8, moddable: true },
    { current: 9, actual: 9, moddable: false },
  ],
  [
    { current: 0, actual: 9, moddable: true },
    { current: 0, actual: 5, moddable: true },
    { current: 7, actual: 7, moddable: false },
    { current: 0, actual: 6, moddable: true },
    { current: 2, actual: 2, moddable: false },
    { current: 0, actual: 8, moddable: true },
    { current: 0, actual: 1, moddable: true },
    { current: 0, actual: 3, moddable: true },
    { current: 0, actual: 4, moddable: false },
  ],
]

export default grid
